make environment generic
o1-labs/proof-systems pull request #1203
Opened 2023-09-05 15:57 UTC by fabrizio-m

2023-09-05 16:00 UTC, fabrizio-m commented
!ci-build-me

2023-10-09 14:41 UTC, querolita approved these changes
Very nice! I just had two doubts, which I am sure wouldn't work. But just asking for curiosity.

2023-10-10 09:42 UTC, querolita requested changes

2023-10-10 09:42 UTC, querolita commented on kimchi/src/circuits/expr.rs
> +    fn vanishes_on_last_4_rows(&self) -> &'a Evaluations<F, D<F>>;
I believe this method should be `vanishing_on_last_n_rows`, which recently changed in develop -> https://github.com/o1-labs/proof-systems/blob/develop/kimchi/src/circuits/expr.rs

Perhaps you have to merge develop onto these branches to get the most recent version.

2024-02-15 12:16 UTC, volhovm commented
Closing, as per @fabrizio-m most of what is useful was already integrated into folding.

2024-02-15 12:16 UTC, closed without merging