map column
o1-labs/proof-systems pull request #1234
Opened 2023-09-08 19:50 UTC by fabrizio-m

makes generic a few trivial implementations and adds the method `map_collum` to all expressions.

2023-09-08 19:51 UTC, fabrizio-m commented
!ci-build-me

2023-10-09 16:28 UTC, querolita approved these changes

2023-10-09 16:28 UTC, querolita commented on kimchi/src/circuits/expr.rs
> +    ///maps expressiosn over some columns to expressions over other columns
nit expressions

2023-10-10 09:46 UTC, querolita requested changes

2023-10-10 09:46 UTC, querolita commented on kimchi/src/circuits/expr.rs
> +            Expr::VanishesOnLast4Rows => Expr::VanishesOnLast4Rows,
Again, here this expression no longer exists in develop. Please get the most updated develop (or wait until we know what to do regarding `develop` vs `master`)

2023-11-17 12:22 UTC, querolita commented
Just a reminder -> I believe we are merging against master instead of develop

2024-02-15 12:16 UTC, volhovm commented
Closing, as per @fabrizio-m most of what is useful was already integrated into folding.

2024-02-15 12:16 UTC, closed without merging