Support for `meta.json` file
o1-labs/proof-systems pull request #1319
Opened 2023-11-03 16:40 UTC by rbonichon

Add symbol to debugging/info output

2023-11-05 21:53 UTC, dannywillems requested changes
LGTM, but would be nice to have a meta.json file example and see if it is parsed correctly with a test

2023-11-06 12:41 UTC, dannywillems commented on optimism/src/cannon.rs
> +            Some("internal/cpu.processOptions".to_string())
```suggestion
            Some("runtime.text".to_string())

```
?

2023-11-06 12:41 UTC, dannywillems commented on optimism/src/cannon.rs
> +            Some("internal/cpu.processOptions".to_string())
Duplicated?

2023-11-06 12:42 UTC, dannywillems commented on optimism/src/cannon.rs
> +        // for e in self.symbols.iter() {
Old?

2023-11-06 12:42 UTC, dannywillems approved these changes
LGTM modulo last comments, but Clippy is grumpy.

2023-11-06 13:14 UTC, rbonichon commented on optimism/src/cannon.rs
> +            Some("internal/cpu.processOptions".to_string())
No. Not testing the same value.

2023-11-06 13:34 UTC, rbonichon commented on optimism/src/cannon.rs
> +        // for e in self.symbols.iter() {
Yep. removed

2023-11-07 08:44 UTC, merged