[master] Bump up to arkwork 0.4.2
o1-labs/proof-systems pull request #1747
Opened 2024-01-23 22:52 UTC by dannywillems

2024-01-25 07:26 UTC, dannywillems commented on kimchi/src/curve.rs
> +        Affine::<PallasParameters>::generator()
It seems we do not need to verify it is in the prime subgroup. But reviewers should check twice.

2024-01-25 07:27 UTC, dannywillems commented on optimism/src/keccak/proof.rs
> +    let proof = prove::<_, OpeningProof, BaseSponge, ScalarSponge>(domain, &srs, proof_inputs);
Mostly simplifying with `OpeningProof`, see alias above.

2024-01-25 07:28 UTC, dannywillems commented on optimism/src/main.rs
> +    let mut folded_witness = proof::ProofInputs::default();
Type annotations are useless.

2024-01-25 07:29 UTC, dannywillems commented on poly-commitment/src/pairing_proof.rs
> +            quotient: Pair::G1Affine::generator().mul_by_cofactor(),
mul_by_cofactor can be removed.

2024-01-25 07:30 UTC, dannywillems commented on poseidon/src/sponge.rs
> +macro_rules! debug_sponge {
I think this can be removed. It comes from the cherry-picking. Reviewers should check.

2024-01-25 07:30 UTC, dannywillems commented on signer/src/pubkey.rs
> +        let pt = CurvePoint::get_point_from_x_unchecked(x, y.0.is_odd())
Note the `unchecked`.

2024-01-25 07:38 UTC, mrmr1993 requested changes
Je rejette ça. 2x slowdown est voudrais lent.

2024-01-25 10:20 UTC, dannywillems commented on curves/src/pasta/curves/tests.rs
> -    let generator = pallas::Pallas::prime_subgroup_generator();
I think we should keep this.

2024-02-13 10:37 UTC, dannywillems commented
Closing as not needed.

2024-02-13 10:37 UTC, closed without merging