add doc about degree 3 folding
o1-labs/proof-systems pull request #2243
Opened 2024-05-17 19:53 UTC by fabrizio-m

2024-05-20 10:07 UTC, volhovm requested changes
@fabrizio-m could you please add all the equations to the doc here? Like how we compute these `t_0` and `t_1` especially.

2024-05-20 11:02 UTC, dannywillems commented
@fabrizio-m: we can discuss about [this](https://github.com/o1-labs/proof-systems/pull/2243#pullrequestreview-2065856409) tomorrow at the offsite. I am happy to guide you on this. We should go through the codebase and the equations together.

2024-05-29 11:27 UTC, querolita commented on folding/src/lib.rs
>  //! That results in 2 errors terms t_0 and t_1 and a slightly different computation
results in 2 error terms

2024-05-29 14:56 UTC, dannywillems commented
Most of the work in https://github.com/o1-labs/proof-systems/pull/2259 has been done by Fabrizio, I was guided by his explanation and he answered my question. I would suggest closing this one, and move on with 2259.

2024-05-29 14:56 UTC, closed without merging