Marc@follow up challenges
o1-labs/proof-systems pull request #2654
Opened 2024-10-03 16:18 UTC by marcbeunardeau88

2024-10-03 19:52 UTC, dannywillems commented
Nit: also a typo in the first commit message

2024-10-03 19:53 UTC, dannywillems commented on kimchi/src/circuits/berkeley_columns.rs
> +/// The challenge terms used in Berkely
Typo

2024-10-04 11:14 UTC, dannywillems reviewed
LGTM for me so far

2024-10-04 15:32 UTC, marcbeunardeau88 commented on kimchi/src/circuits/berkeley_columns.rs
> +/// The challenge terms used in Berkely
fixed up

2024-10-04 15:36 UTC, dannywillems approved these changes

2024-10-04 15:54 UTC, dannywillems requested changes
The PR doesn't compile.

2024-10-07 13:41 UTC, merged