[kimchi][bench] better bench + guideline for flamegraph
o1-labs/proof-systems pull request #268
Opened 2022-01-19 06:12 UTC by mimoo

* Decreased the number of iterations for benchmarks to 10 (otherwise it takes too much time). 
* Also, separated bench for proving and verifying
* The bench now uses a circuit of 2^16 gates. Should I increase this? I think we might be at 2^17 or 2^18 for Mina. Ideally I would bench different sizes but I don't think our poor-man CI will like that
* Some indications on how to produce a flamegraph

2022-01-21 15:28 UTC, mrmr1993 requested changes

2022-01-21 19:13 UTC, mimoo commented on circuits/kimchi/src/gate.rs
> +    #[allow(clippy::type_complexity)] // TODO: fix this clippy
I was thinking of using a tool to track TODOs, so I still think they should be TODOs (so we don't have to special case the allow(clippy)), but I can create another PRs for that if that's bothering you :D

2022-02-07 22:37 UTC, mimoo commented on circuits/kimchi/src/gate.rs
> +    #[allow(clippy::type_complexity)] // TODO: fix this clippy
ping

2022-02-07 22:37 UTC, mimoo commented
Our verifier circuit is now 2^15, so it might be a good idea to change the bench to 2^15 instead of the 2^16... wdyt?

2022-02-11 17:56 UTC, mrmr1993 commented on kimchi/src/circuits/gate.rs
> +    #[allow(clippy::type_complexity)] // TODO: fix this clippy
Delete this TODO comment

2022-02-11 17:56 UTC, mrmr1993 commented on kimchi/src/circuits/polynomials/lookup.rs
> +#[allow(clippy::too_many_arguments)] // TODO: fix this clippy
Delete this TODO comment

2022-02-11 17:56 UTC, mrmr1993 commented on kimchi/src/circuits/polynomials/lookup.rs
> +#[allow(clippy::too_many_arguments)] // TODO: fix this clippy
Delete this TODO comment

2022-02-11 17:56 UTC, mrmr1993 commented on kimchi/src/circuits/polynomials/permutation.rs
> +    #[allow(clippy::type_complexity)] // TODO: fix this clippy
Delete this TODO comment

2022-02-11 17:56 UTC, mrmr1993 commented on kimchi/src/circuits/polynomials/varbasemul.rs
> +#[allow(clippy::too_many_arguments)] // TODO: fix this clippy
Delete this TODO comment

2022-02-11 17:56 UTC, mrmr1993 commented on kimchi/src/verifier.rs
> +    #[allow(clippy::type_complexity)] // TODO: fix this clippy
Delete this and remaining TODOs in the PR

2022-02-11 18:57 UTC, mimoo commented
@mrmr1993 done!

2022-02-11 19:59 UTC, mrmr1993 approved these changes

2022-02-11 20:23 UTC, merged