Marc/uncombine cons per instr
o1-labs/proof-systems pull request #2701
Opened 2024-10-10 16:32 UTC by marcbeunardeau88

2024-10-14 09:12 UTC, dannywillems requested changes
See comment. Change PR state as draft.

2024-10-14 09:12 UTC, dannywillems commented on o1vm/src/pickles/main.rs
> +                /*  // padd the acc or constraint to the same length
I guess it is not ready.

2024-10-14 09:23 UTC, marcbeunardeau88 commented on o1vm/src/pickles/main.rs
> +                /*  // padd the acc or constraint to the same length
removed commented code

2024-10-27 07:54 UTC, dannywillems commented
@marcbeunardeau88 can you fix the conflicts and rebase on master? We do have now the prover + e2e tests in the CI; I was waiting for this to get a second look here.

2024-12-05 08:27 UTC, closed without merging