fixing the parsing and constraint generation for sbtype instructions
o1-labs/proof-systems pull request #2855
Opened 2024-12-01 21:41 UTC by svv232

2024-12-02 16:09 UTC, martyall commented on o1vm/src/interpreters/riscv32im/interpreter.rs
> +        env.range_check8(&imm11, 1);
It seems strange that we check that a single "bit" is in range `[0,255]`, or am i misunderstanding the point?

2024-12-19 15:28 UTC, dannywillems commented on o1vm/src/interpreters/riscv32im/interpreter.rs
> +    /* fetch instruction pointer from the program state */
Not sure we need these comments, but ok.

2024-12-19 15:28 UTC, dannywillems commented on o1vm/src/interpreters/riscv32im/interpreter.rs
> +        env.range_check8(&imm11, 1);
There should be a single `is_boolean` method.

2024-12-19 15:28 UTC, dannywillems commented on o1vm/src/interpreters/riscv32im/interpreter.rs
> +        env.range_check8(&imm12, 1);
Same: use `is_boolean`.

2024-12-19 15:29 UTC, dannywillems commented on o1vm/src/interpreters/riscv32im/interpreter.rs
> +    /* fetch opcode from instruction bit 0 - 6 for a total len of 7 */
Should we get rid of these comments?

2024-12-19 15:29 UTC, dannywillems commented on o1vm/src/interpreters/riscv32im/interpreter.rs
> +    // extra bit is because the 0th bit in the immediate is always 0 i.e you cannot jump to an odd address
I guess it is used somewhere after.

2024-12-19 15:30 UTC, dannywillems requested changes
See previous comment

2024-12-23 20:15 UTC, svv232 commented on o1vm/src/interpreters/riscv32im/interpreter.rs
> +    // extra bit is because the 0th bit in the immediate is always 0 i.e you cannot jump to an odd address
yes it is used in future prs

2024-12-23 20:19 UTC, dannywillems approved these changes

2024-12-23 20:37 UTC, dannywillems approved these changes

2024-12-24 09:15 UTC, merged