Makefile: target to import all programs from Optimism
o1-labs/proof-systems pull request #2906
Opened 2024-12-23 17:48 UTC by dannywillems

2024-12-24 18:56 UTC, martyall requested changes
This  is super useful! My only comment is that the linked files shouldn't be committed, so basically the entire `resources/programs/mips/bin` directory should be ignored (not just the object files). It seems like this was also your intention since `make clean` blows this directory away.

2024-12-24 19:56 UTC, dannywillems commented
> This is super useful! My only request is that the linked files shouldn't be committed, i.e. the entire `resources/programs/{mips,riscv}/bin` directory should be ignored (not just the object files). It seems like this was also your intention since `make clean` blows this directory away.

The only issue I see by not committing them is that the CI (and users) will have to build them, and therefore would need to add the mips toolchain on their machine.

2024-12-24 20:30 UTC, martyall commented
> The only issue I see by not committing them is that the CI (and users) will have to build them, and therefore would need to add the mips toolchain on their machine.

That's a fair points about its annoying to require it for devs, it just seems weird that running `make clean` creates a diff by deleting them.

BTW I can confirm that these are working with #2911 .

2024-12-26 21:22 UTC, martyall commented
@dannywillems I would suggest that we use a github workflow with a `workflow_dispatch` trigger to be able to run this job in ci and tar/upload the artifacts. This way we can still ignore the `bin` directory and `make clean` is really clean (as opposed to "dirty"). 

You can see what this looks like [here](https://github.com/o1-labs/proof-systems/actions/runs/12508373496/workflow), and here is an [example upload](https://github.com/o1-labs/proof-systems/actions/runs/12508373496/job/34896394289#step:7:20)

2025-01-02 09:57 UTC, dannywillems commented
I did remove the commit https://github.com/o1-labs/proof-systems/commit/49235d338ff233dc29a2809b0d179f603b657301 to clean the history and avoid unnecessary commits. https://github.com/o1-labs/proof-systems/pull/2911 would therefore need a rebase.

2025-01-02 17:22 UTC, martyall approved these changes

2025-01-02 17:34 UTC, merged