[snarky-rs] add Sys to Var
o1-labs/proof-systems pull request #596
Opened 2022-06-03 23:32 UTC by mimoo

This is a proposal to add `Sys: Cs` to `Var` in the circuit writer.

Essentially, we need to pass a main `sys` around all the time to do interesting things with our variables (like add two variables together). It's a bit annoying, so this PR adds a pointer to `sys` in vars so you can just do things like:

```rust
    let x1 = sys.var(|| F::one());
    let x2 = sys.var(|| F::one());
    let x3 = x1 + x2;
    let two = sys.constant(F::from(2u32));
    sys.assert_eq(x3, two);
```

instead of

```rust
    let x1 = sys.var(|| F::one());
    let x2 = sys.var(|| F::one());
    let x3 = sys.add(x1, x2);
    let two = sys.constant(F::from(2u32));
    sys.assert_eq(x3, two);
```

I'm actually not convinced that it's the best idea, as it makes the code a bit more complicated/verbose for a marginal gain. But perhaps it is still a good idea if we push this further. What do people think? Maybe I took a more complicated than necessary approach also.

2022-06-04 00:02 UTC, mimoo commented
cc @katat

2022-06-05 17:28 UTC, mrmr1993 requested changes
If we're doing this, we should make sure that the `sys` field is the same for both variables when we use it.

2022-06-05 17:28 UTC, mrmr1993 commented on circuit-construction/src/lib.rs
> +    pub sys: Sys,
If this is supposed to be a pointer, make it one. The `Arc<Rc<Sys>>` should be an implementation detail.

2022-06-05 17:28 UTC, mrmr1993 commented on circuit-construction/src/lib.rs
> +/// ?
This is not a useful change; delete

2022-06-05 17:28 UTC, mrmr1993 commented on circuit-construction/src/lib.rs
> +/// Represents a gate before compilation.
Don't add doc-comments as part of other unrelated changes.

2022-06-05 17:28 UTC, mrmr1993 commented on circuit-construction/src/lib.rs
> +type Ref<Sys> = Rc<RefCell<Sys>>;
Shouldn't we try to be thread-safe?

2022-06-08 15:49 UTC, mimoo commented
waiting on feedback for https://github.com/o1-labs/proof-systems/pull/605 which should simplify this approach

2022-08-08 14:27 UTC, closed without merging