[curves] introduce wrappers for Fp and Fq
o1-labs/proof-systems pull request #765
Opened 2022-09-26 20:09 UTC by mimoo

2022-09-26 20:16 UTC, mimoo commented
looks like no overhead detected:

```
Proof creation/proof creation (SRS size 2^15)                                                                          
                        time:   [3.3081 s 3.3659 s 3.4263 s]
                        change: [-0.7666% +2.6613% +5.8995%] (p = 0.15 > 0.05)
                        No change in performance detected.
```

(compare with https://github.com/o1-labs/proof-systems/pull/750)

2022-09-26 21:18 UTC, mrmr1993 approved these changes
Really nice!
As a sanity check, it would be good to make a Mina PR and make sure that CI is happy there

2022-09-26 22:46 UTC, mimoo commented
playing with it here: https://github.com/MinaProtocol/mina/pull/11906

it seems to compile the stubs. Not sure if mina compiles yet, and haven't touched the wasm part.

2022-09-28 19:28 UTC, mrmr1993 requested changes
See comment. Can you rework this so that it's only moving the OCaml types into this repo, and leave the rest on the Mina side?

2022-09-28 19:28 UTC, mrmr1993 commented on curves/src/pasta/arkworks/fields.rs
> +                pub fn [<$name:snake _size_in_bits>]() -> ocaml::Int {
Per my message OOB: I don't think the bindings for Mina should live here. The behaviour and API are mina-specific, but this library is supposed to be general-purpose.

2022-12-05 20:37 UTC, mimoo commented
probably we should try this approach first: https://github.com/arkworks-rs/algebra/pull/506

2022-12-06 00:42 UTC, mimoo commented
ping @mrmr1993

2022-12-06 00:45 UTC, mimoo commented
urg actually I don't think this will solve all of our problems for serde at least... Because things like `G::Scalar` are not bound by `Serialize/Deserialize`. We might have to do the same for `AffineCurve`

2022-12-13 07:22 UTC, closed without merging