Remove ChaCha gate as it's now unneeded
o1-labs/proof-systems pull request #971
Opened 2023-01-27 21:07 UTC by jspada

As discussed with Matthew, with our new approach in zkoracles, this gate is not longer required and should be removed for simplicity and performance.  Removing this will also mean less work to do for verification of custom gates in wrap proofs.

2023-01-27 21:27 UTC, mrmr1993 approved these changes

2023-01-27 23:17 UTC, mimoo commented
are we sure that zkapps will never have a need for this? It sounded like a nice thing to have :o

2023-02-08 06:32 UTC, mimoo requested changes
cf my previous comment, but also please update the CHANGELOG.md in kimchi before getting this in! we have a CHANGELOG now :)

2023-02-14 16:14 UTC, mrmr1993 approved these changes

2023-02-14 17:19 UTC, merged